server:
  port: 8081

spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ley?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间
    lease-expiration-duration-in-seconds: 5 #过期时间

mybatis:
  type-aliases-package: com.leu.item.pojo